### ISSUE TITLE
SSL connection failed: session reuse required

### ISSUE THREAD

**Issue by SrVince** [satiromarra/vscode-sftp#1]
**Do you read the FAQ?**
- [x] Yes.
- [x] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
When try connect to ftp with ssl self-signed, return "session reuse required"

My config:

    "protocol": "ftp",
    "secure": true,
    "secureOptions": {"rejectUnauthorized": false},
    "port": 21,

Can you help me? Thanks.

**Comment by satiromarra** [comment]
Have you tried without "secure" and "secureOptions"?

**Comment by satiromarra** [comment]
@SrVince 
I have tested a configuration like this on an ftp server with tls function and a self signed certificate and it connects correctly.
```json
{
  "name": "xxx",
  "password": "xxx",
  "username": "xxx",
  "host": "xxx",
  "protocol": "ftp",
  "port": 21,
  "secure": true,
  "secureOptions": {"rejectUnauthorized": false}
}
```
Tries:
- Enable Debug in Settings and show the output tab.
- Your connection in FileZilla

**Comment by satiromarra** [comment]
@SrVince tries these options:
```json

  "secure": true,
  "secureOptions":  {"rejectUnauthorized": false, "secureProtocol" :"TLSv1_2_method"}

```

**Comment by SrVince** [comment]
> 

That was it, I asked the owner of the server to edit the file "/etc/vsftpd.conf" of the server and add require_ssl_reuse=NO.

Thanks!

**Comment by SergeySch** [comment]
Hi, is there any chance to fix this issue? I am trying to connect to Filezilla FTP server using the same settings as topic starter, and it returns error "TLS session of data connection not resumed" after successful login (NOOP command is also performing ok).
