### ISSUE TITLE
vscode를 여러개 띄워서 각각 다른 remote에 연결해서 쓰고 싶어

### ISSUE THREAD

**Issue by gusqlslee** [satiromarra/vscode-sftp#10]
안녕! 
새로운 기능을 제안하고 싶어!
물론 내가 지금 제안하려는 기능이 벌써 있을지도 모르겠다 라는 생각은 해보긴 했어, 하지만 난 슬프게도 그 기능을 찾을 수 없었어.
그래서 제안해보려고 해!

난 한국에서 작은 회사의  backend 개발자로 있으며 
PHP언어를 주로 쓰고 내가 속해 있는 회사의 관리 프로그램들과 많은 서비스들의 DB관리와 API관리를 하고 있어.

내가 속해있는 회사는 작지만 많은 서비스를 하고 있어
통신 관련 업체인데 트래픽 소모량이 많아.

그래서 여러 서비스를 왔다 갔다 하면서 유지보수 작업과 새로운 작업을 하는데
서비스 사이를 왔다 갔다 하는 걸 꽤 반복해야 해서 윈도우 11의 멀티 모니터를 여러게 열어 놓고
모니터를 왔다 갔다 하면서 작업하는 편이야.

ATOM을 쓸때는 각 에디터별로 remote 연결을 모두 띄워 놓고 작업할 수 있었는데
vscode는 어떻게 해야할지 모르겠어,

얼마전에 ATOM이 서비스 종료되면서
vscode를 써본지 한달도 채 안되거든.

vscode는 아톰 초기와 같이 프롬프트를 주로 써가며 확장 기능을 사용해야 하잖아.
난 이런 vscode가 너무 맘에 안들어서 거의 10년동안 atom만 썼어

vscode 따위 쓰고 싶지 않았어.
너무 외워야 할 명령어들이 많았으니까.

그래서 satiro 가 만들어준 SFTP는
나에게 vscode를 써봐야 겠다고 생각하게된 유일한 이유야!

remote test 서버에 바로 붙어서 작업해야 하는데
remote를 계속 커멘드를 쳐가며 왔다 갔다 하는 일이 정말 맘에 안들었거든.

근데 고민인게 vscode를 여러게 띄워 놓으면 단 한군데에서만 sftp를 쓸 수 있어.
난 모든 vscode 에디터에 각각 다른 sftp 목록을 불러다가 작업하고 싶어!

어때 나의 제안이?!

쓸모 있다고 생각해!

satiro! 읽어줘서 고마워!!

**Comment by satiromarra** [comment]
@gusqlslee  You can explain this in English?

**Comment by satiromarra** [comment]
@gusqlslee I understand that you need to have a project for each open vscode and each project an ftp configuration, right?
