### ISSUE TITLE
Sort connections alphabetically when grouped by host

### ISSUE THREAD

**Issue by ghost** [satiromarra/vscode-sftp#11]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [X] No.

**Is your feature request related to a problem? Please describe.**
Right now there are three grouping options: group by host, group by folder, and list connections.  However, there are no sorting options.

**Describe the solution you'd like**
The ideal solution:
Add sorting options for the grouping options (by host and by folder):
1. Default sort (the current sort, which I believe is just the order in which the config is setup)
2. Alphabetically (A-Z)
3. Alphabetically (Z-A)

The less ideal solution: always sort alphabetically.

**Describe alternatives you've considered**
Alternatively, I could use the third grouping option which automatically lists connections alphabetically.

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

**Comment by satiromarra** [comment]
Great idea!

**Comment by satiromarra** [comment]
@MKaidan New feature included in 1.17.9 version ;)

**Comment by ghost** [comment]
Amazing! Thank you!!
