### ISSUE TITLE
Show .htaccess files

### ISSUE THREAD

**Issue by olivdee** [satiromarra/vscode-sftp#2]
Since there was no fix for showing the .htaccess files on the server for the https://github.com/Natizyskunk/vscode-sftp, I was wondering if this works with your fork, or if this could be implemented here. As described @Natizyskunk/vscode-sftp, there is no server or config-issue, as .htaccess files are showing up on other FTP-Software (like Filezilla), without the need to adjust any server-config at all. Switched tried ftp & sftp protocol, as well as all suggested solutions @Natizyskunk/vscode-sftp - but no luck so far. Any idea/suggestion?

**Comment by satiromarra** [comment]
There is no restriction or limitation for displaying dotfiles, as can be seen in the attached image.
<img width="289" alt="image" src="https://user-images.githubusercontent.com/1863162/219700868-0e8a85bd-58a1-41bc-9885-3333ec1b38ad.png">

Can you provide more information?

**Comment by olivdee** [comment]
What kind of information do you need?

I just checked on projects with different servers, and for example it works with SiteGround & Hetzner.com, but not on a server with Plesk/Obsidian. 
1) It works for that server though if I try it with Filezilla! 
2) The related hosting provider also states that there is no setting with Plesk that allows or blocks dotfiles. 

Because of those two reasons I am suspecting the problem to be with VScode or the SFTP extension. 
 
Any idea?

**Comment by satiromarra** [comment]
@olivdee I have tested the extension using the configuration with a windows server with Plesk Obsidian 18.0.50.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/1863162/220728610-cc65d7fd-847a-450d-8c45-a15c7b0c7cd6.png">

You can try enabling the options: "sftp: debug" and "sftp: print debug log" and see what might be happening.
If there are any lines showing errors, remove the sensitive data and share the log.

**Comment by olivdee** [comment]
Made the changes in "Settings", restarted VScode, "Refreshed" even the server in the SFTP panel, but no luck, the .htaccess is not showing up... 
![Screenshot 2023-02-22 204506](https://user-images.githubusercontent.com/2912892/220742506-efd7c6ec-72ed-4a66-abbd-bf0d7f29fd4b.png)
And DEBUG CONSOLE is also empty as you can see on the above screenshot - or do I need to get the logs from somewhere else???

The only difference I can spot inside sftp.json is on mine "uploadOnSave" is set to false.

And YES, the .htaccess exists on the server, here a screenshot from within Plesk File Manager:
![Screenshot 2023-02-22 205258](https://user-images.githubusercontent.com/2912892/220743694-84163f50-e229-4641-81c3-dd9d055005be.png)
The two dotfiles (RED) are not visible in SFTP, the other two (GREEN) starting with "_" are visible, even though all have the same rights (YELLOW).

**Comment by satiromarra** [comment]
I have created and uploaded the new version "1.17.5" which includes the option "sftp.verbose" to see more information.

1. Open User Settings.
  - On Windows/Linux - `File > Preferences > Settings`
  - On macOS - `Code > Preferences > Settings`
2. Set `sftp.printVerboseLog` to `true` and reload vscode.
3. View the logs in `View > Output > sftp`.

Then go to remote explorer and open the directory to show the list of items, then check the log for ".htaccess":

```
[2023-02-22 22:42:07] [verbose] Listing folder '/'
[2023-02-22 22:42:07] [verbose] Exclude list: '.git, .svn, .hg, CVS, .DS_Store'
[2023-02-22 22:42:07] [verbose] File: .gitignore | Size: 9 B | Modified: 2023-02-22 22:22:00
[2023-02-22 22:42:07] [verbose] File: .htaccess | Size: 0 B | Modified: 2023-02-22 21:30:00
....
[2023-02-22 22:42:07] [verbose] -> File '.gitignore' is in ignore list? -> No
[2023-02-22 22:42:07] [verbose] -> File '.htaccess' is in ignore list? -> No
....
```

**Comment by olivdee** [comment]
did all that, log works but shows all files except the two dotfiles...

**Comment by satiromarra** [comment]
@olivdee can you test this version?
[code-sftp-1.17.6.zip](https://github.com/satiromarra/vscode-sftp/files/10817339/code-sftp-1.17.6.zip)

Add to your configuration 
```json
"showHidden": true,
```
(or edit connection with ui):
<img width="420" alt="image" src="https://user-images.githubusercontent.com/1863162/221008175-6a01c787-6311-4ca5-a4da-f519d368bac9.png">

* I think it is because some servers have to be forced to show hidden files.

**Comment by olivdee** [comment]
first of all thank you so much so far!
will check ASAP and report back

**Comment by olivdee** [comment]
BOOM! GRCS!!!
Very nice my friend, it works now.

May I ask why you forked Natizyskunk's SFTP? 
Any additional features?

**Comment by satiromarra** [comment]
Some of the new features:
- Rename remote Files and Folders
- Multiple configurations with multiples profiles
- Change remote permission in folder and files
- Download files and folders as another name
- Create/Edit connections with User Interface
- Configure charset to ASCII in Ftp protocol.

and now "Fixed, list hidden files on ftp connections." ;)

**Comment by olivdee** [comment]
Great stuff, you should mention those right on top, in order for someone to see the differences/additions!
Say, doesnt Buy-Me-A-Beer work with PayPal? Or, are there PayPal donations possible?

**Comment by satiromarra** [comment]
> Great stuff, you should mention those right on top, in order for someone to see the differences/additions!

Lot a thanks ;)
Set the section as?
```
New features:
...
Features:
...
```



> Say, doesnt Buy-Me-A-Beer work with PayPal? Or, are there PayPal donations possible?

buymeacoffee seems to only work with stripe; and about PayPal, yes, there is the link in the info.


Thanks for all.
