### ISSUE TITLE
View images - like a local folder

### ISSUE THREAD

**Issue by ghost** [satiromarra/vscode-sftp#32]
**Is this a similar or duplicate feature request?**
- [ ] I don't know. I will go check it.
- [X] No.

**Is your feature request related to a problem? Please describe.**
When I click on a file, such as a PHP file, it opens the file in a tab. When I click on an image file, I get an error:

> Detail: File seems to be binary and cannot be opened as text

**Describe the solution you'd like**
Image files should open up in a tab just like they do in a local folder/directory.

**Describe alternatives you've considered**
Download the file and open locally, which requires more steps and can be avoided.

**Does this project help you?**
- [x] Yes. SFTP IS AWESOME!

**Comment by satiromarra** [comment]
@MKaidan I have been working on this improvement for quite some time and I have not achieved anything that would satisfy me, and I have left it aside. Opening any media file can cause problems, in this case we are talking about images, but video files that occupy several megas or gigas?
What I thought was to restrict the opening of media files, that is, that when you select it you don’t do anything.

**Comment by ghost** [comment]
Why not start with getting images to work, and then worry about video?

What is the concern with video exactly? Timeout when downloading the file from the server?

**Comment by satiromarra** [comment]
@MKaidan Video or any other type of large file. I’ll try to do some.

**Comment by satiromarra** [comment]
@MKaidan Can you try this beta? [v1.17.11-beta1](https://github.com/satiromarra/vscode-sftp/releases/download/v1.17.11-beta1/code-sftp-1.17.11-beta1.vsix)

**Comment by ghost** [comment]
The beta still gives me an error when I try to open an image file:
`cannot open file://[file path]. Detail: File seems to be binary and cannot be opened as text`

**Comment by satiromarra** [comment]
@MKaidan What image extension?

**Comment by ghost** [comment]
.jpg, .png, and .gif

**Comment by satiromarra** [comment]
@MKaidan Among other things, I have uploaded a new beta with some more checks.
When a file is selected and its extension is in the list of images, the temporary image is downloaded and opened.
`['.jpg', '.jpeg', '.svg', '.bmp', '.png', '.gif', '.tiff']`
<img width="807" alt="Captura de pantalla 2023-04-14 a las 18 31 03" src="https://user-images.githubusercontent.com/1863162/232103085-b63b6cea-1d98-42b6-ac3b-da20691b9a5b.png">

Try [beta3](https://github.com/satiromarra/vscode-sftp/releases/download/v1.17.11-beta3/code-sftp-1.17.11-beta3.vsix) and let me know.

**Comment by ghost** [comment]
That's strange - I still cannot open any of those files.

**Comment by ghost** [comment]
I should mention that the SFTP folder that I'm in, is on a local server in my office. So the files are not on my local drive but on the server which I have access to. I'm not sure if that should be a problem because all text files open, but I thought I should let you know.

**Comment by ghost** [comment]
Also this is a Windows environment, not Mac or Linux.

**Comment by satiromarra** [comment]
Try: 
- Uninstall the extension
- Close and Start vscode (not reload)
- Install the beta3.

> I should mention that the SFTP folder that I'm in, is on a local server in my office. So the files are not on my local drive but on the server which I have access to. I'm not sure if that should be a problem because all text files open, but I thought I should let you know.

No problem, That's the idea to open the remote images.

> Also this is a Windows environment, not Mac or Linux.

Coincidentally the OS I don't use :P

**Comment by ghost** [comment]
Still the same.

**Comment by MKaidan** [comment]
```
[2023-04-14 13:57:26] [info] remote ➞ local \\mkserver3\users\Aidan\Documents\VS Code SFTP\project\kordvani_realty\assets\images\KR_Logo_Text.png
[2023-04-14 13:57:26] [error] Error: cannot open file://mkserver3/users/Aidan/Documents/VS%20Code%20SFTP/project/kordvani_realty/assets/images/KR_Logo_Text.png. Detail: File seems to be binary and cannot be opened as text
    at u.$tryOpenDocument (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2334:37824) 
```

**Comment by satiromarra** [comment]
The message `[2023-04-14 13:57:26] [info] remote ➞ loca ...` should not come out when you select a remote image in "Remote Explorer"

<img width="937" alt="Captura de pantalla 2023-04-14 a las 20 15 09" src="https://user-images.githubusercontent.com/1863162/232125614-3aa1429e-34e0-49cd-b15b-eb416b621f27.png">

**Comment by ghost** [comment]
Sorry, I should have specified I turned on logging to see what was happening. That was what the log told me.

Here's what I'm seeing:
[redacted]

**Comment by satiromarra** [comment]
Is this option disabled?

<img width="537" alt="image" src="https://user-images.githubusercontent.com/1863162/232135490-e5fdafe2-a05f-4c24-a3ce-9a49186a8b5c.png">

**Comment by ghost** [comment]
It's enabled.
![image](https://user-images.githubusercontent.com/77799466/232135770-04443835-0a75-40ae-96e3-334c0338c6bf.png)

**Comment by ghost** [comment]
When I disable it, close, and reopen VS Code, I now see this:
[redacted]

**Comment by satiromarra** [comment]
That is the cause of the problem, i have not considered that option.

I have reuploaded the [beta3](https://github.com/satiromarra/vscode-sftp/releases/download/v1.17.11-beta3/code-sftp-1.17.11-beta3.vsix) version again with some improvements.
Enable: Download When Open In Remote Explorer

**Comment by ghost** [comment]
It's working perfectly now!

Will you be releasing this version?

**Comment by satiromarra** [comment]
Yes, with some improvement, it will be published shortly in version 1.17.11.

**Comment by ghost** [comment]
Thank you, I meant a GitHub release as well though.

**Comment by ghost** [comment]
Also the popup "We're working on previewing images" still comes up. @satiromarra

**Comment by satiromarra** [comment]
😫
