### ISSUE TITLE
Can I know how to compile .vsix

### ISSUE THREAD

**Issue by AydenLin1022** [satiromarra/vscode-sftp#33]
HI, after I typed "vsce package", I have been unable to package the .vsix file correctly.
Am I missing any steps?

My step:
1.git clone https://github.com/satiromarra/vscode-sftp.git
2.npm install
3.vsce package  (fail)

![image](https://user-images.githubusercontent.com/39587407/231922527-6856e17d-ed58-4979-a64a-918b9b40281b.png)

**Comment by satiromarra** [comment]
@AydenLin1022 You must do the installation of npm with the same versions that are in the package.json, otherwise it will install major updates.

From stackoverflow:

> By default npm installs packages using ^ which means any version in the same major range, you can switch this behaviour by using --save-exact

**Comment by AydenLin1022** [comment]
@satiromarra Okay, I do installation of npm with the same versions now! but still fail ~ 
Here 833 errors
![image](https://user-images.githubusercontent.com/39587407/231990733-5c09417a-eeac-46bf-9f94-8e83107ed989.png)

And now I find problem, here commit (v1.17.11-beta1) always compile fail
![image](https://user-images.githubusercontent.com/39587407/231989472-7c21dd6a-3611-4e83-9667-5ddb13d78d0b.png)

So I checkout commit to here (v1.17.0)
![image](https://user-images.githubusercontent.com/39587407/231989591-a12812db-34ee-4b0c-a1ae-efdd59fe20ca.png)

Now is work! 
![image](https://user-images.githubusercontent.com/39587407/231991820-7268d675-d1db-45cb-9584-333034223882.png)

**Comment by satiromarra** [comment]
Possibly dependantbot has failed in something.

**Comment by AydenLin1022** [comment]
Yeah, maybe, hope the next version will be better!
Thank you!
