### ISSUE TITLE
Error: Warn when uploading over newer file  (different time zone)

### ISSUE THREAD

**Issue by SrVince** [satiromarra/vscode-sftp#34]
**Do you read the FAQ?**
- [x] Yes.
- [x] [I am going to read now.](https://github.com/satiromarra/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
How to disable "Warn when uploading over newer file."? My server has one time zone and my computer another, which means that it always shows me the alert.

**Comment by satiromarra** [comment]
@SrVince  in sftp.json whit the option `remoteTimeOffsetInHours`, if the server has -2 hours, set `remoteTimeOffsetInHours: -2`.

**Comment by satiromarra** [comment]
@SrVince I just added an option to activate/deactivate that option in version 1.17.12

**Comment by SrVince** [comment]
Thanks! ♥
