### ISSUE TITLE
Can't work uploadOnSave

### ISSUE THREAD

**Issue by onlulatte** [satiromarra/vscode-sftp#35]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/satiromarra/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
 - I can't use `uploadOnSave` that I used well until the previous version.

**To Reproduce**

![2023-04-17 10 03 42](https://user-images.githubusercontent.com/97737793/232355543-fbd74138-c949-4598-a372-ad6c31467d46.jpg)  
I'm setting and using the screenshot above.  

![GIF 2023-04-17 오전 9-45-40](https://user-images.githubusercontent.com/97737793/232355646-f6d7c75f-b0b6-46d0-9a31-4195491d4652.gif)  

So when I saved it, it was uploaded on a remote server. (version 1.17.11)  

![GIF 2023-04-17 오전 9-46-47](https://user-images.githubusercontent.com/97737793/232355651-b98c1a1d-a378-44b4-874e-a097016d3eb6.gif)  

However, there is no change in saving from version 1.17.12.  
Please fix it.

**Desktop (please complete the following information):**
 - OS: Win10
 - VSCode Version 1.77.3
 - Extension Version 1.17.12

**Comment by satiromarra** [comment]
@onlulatte I have uploaded the fix in version 1.17.14

**Comment by UmbrellaProject** [comment]
using version 1.18.1 no matter what i do uploadOnSave does not work
