### ISSUE TITLE
Show active Profile in Statusbar

### ISSUE THREAD

**Issue by j-kinz** [satiromarra/vscode-sftp#37]
Hi Satiro,

is it possible to add the active Profilename in the statusbar on the bottom (e.g. next to the "SFTP")?

In my case I have 3-4 different Profiles and to check which one is active I always need to check via the "Set Profile"-Command or with the open Output in the bottom where I prefer the terminal.

Thank you for your work on the SFTP-Addon!

**Comment by satiromarra** [comment]
I'll write it down to correct it. If you set a name to the profile, it will be used as the connection name in "Remote Explorer".

In my case I have projects with multiple connections with several profiles, it is complicated which connection to show in the status bar.

**Comment by j-kinz** [comment]
Thank you for the hint. I didn't know about the "Remote Explorer"-Name.

**Comment by satiromarra** [comment]
Anyway, I upload an update, it will show in the status bar the profile to which a file belongs when it is opened.

**Comment by satiromarra** [comment]
@j-kinz Does the latest update do what you need?

**Comment by j-kinz** [comment]
Yes. Thank you for the fast implementation. 

The "Profile: "-part may be unnecessary but the main problem is solved.

<img width="138" alt="image" src="https://user-images.githubusercontent.com/28043485/232873700-6ac79e6e-9077-4d53-b833-194af9bf05a6.png">
