### ISSUE TITLE
File Watcher Array

### ISSUE THREAD

**Issue by evtimov** [satiromarra/vscode-sftp#39]
Hi @satiromarra,

This request is **not related to a problem** and it isn't a duplicate feature request.

Do you think it's possible to add an option to set multiple file locations in the watcher config? For example I **_only_** need to watch the `/project/css/them*{.scss,.css,.map}` files and **_all files_** inder the `/project/js/` folders for changes and auto upload if any.

I would image something like this if possible:

```
"watcher": {
    "files": [
          "**/project/css/them*{.scss,.css,.map}",
          "**/project/js"
    ],
    "autoUpload": true,
    "autoDelete": false
}
```

If there is another way to achieve this, please let me know. 

Thank you!

**Does this project help you?**
[x] Yes. SFTP IS AWESOME!

**Comment by satiromarra** [comment]
I use a configuration like this, in case it can work for you:
`/project/{css,js}/{them*,otherfile*}{.scss,.css,.map,.ts,.js}`

**Comment by evtimov** [comment]
Oh I see, yes perfect, thank you.
