### ISSUE TITLE
Error during write to file

### ISSUE THREAD

**Issue by evtimov** [satiromarra/vscode-sftp#43]
Hi @satiromarra 

I have experienced a weird extension behaviour which I no longer can replicate. I was working for at least an hour on that file when suddenly the FTPS stopped uploading the file changes. 

I have attached an image with the error log visible.  The funny thing is that it all started working again after about 5 minutes of plugin inactivity as I was away from the workstation.

Please ignore if you think it was a one off thing.

![bug](https://user-images.githubusercontent.com/47464444/234292909-673e7c80-7ee4-4868-87c1-caa140e75e5b.jpg)

**Comment by satiromarra** [comment]
@evtimov After investigating for a while and the little I have found, the error: "Error during write to file" && "Transfer aborted" && "x.xx seconds (measured here), x.xx Kbytes per second" (3 lines of error) is returned by the FTP server.

Most users say: "no space left on the server." Can you verify that information?

**Comment by evtimov** [comment]
### Yes, I can confirm that was the issue!  

![disk-space](https://user-images.githubusercontent.com/47464444/234356030-0879a29f-6e28-4a5e-a2bb-4b1a00a4173d.jpg)

It might be a good idea (if possible) to change the error message saying something like this?

**`Failed to write file to disk. Perhaps file destination is not writable (blocks/inode limit exceeded) or the disk space is full.`**

Many thanks.

**Comment by satiromarra** [comment]
I can do that if the error messages are: "Error during write to file" && "Transfer aborted" I replaced them with another message that says: "Failed to write file to disk in destination, blocks, inodes or bandwidth limit exceeded or the disk space is full."

Maybe in next release.

**Comment by evtimov** [comment]
That would be great, thank you.

**Comment by satiromarra** [comment]
Well, here is the [alpha](https://github.com/satiromarra/vscode-sftp/releases/download/v1.17.17-alpha1/code-sftp-1.17.17-alpha1.vsix) version ;)

... and thanks for the support 🎉🎉🎉
