### ISSUE TITLE
Protocol FTP

### ISSUE THREAD

**Issue by laborer123** [satiromarra/vscode-sftp#54]
**Do you read the FAQ?**
- [✓] Yes.
- [ ] [I am going to read now.](https://github.com/satiromarra/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Only FTP is unavailable， “Timeout while connecting to server”

**To Reproduce**

**Expected behavior**
I need to use FTP to transfer ascii files to avoid errors on different platforms.

**Screenshots**
![image](https://github.com/satiromarra/vscode-sftp/assets/70676318/6cd5e669-22f6-45f4-bd1e-3ed7681577d0)
![image](https://github.com/satiromarra/vscode-sftp/assets/70676318/62bada15-3ca2-4f82-89e1-0e83b27e6ebf)

**Desktop (please complete the following information):**
 - OS: [Win, Linux]
 - VSCode Version [e.g. 1.77.1]
 - Extension Version [e.g. 1.18.0]

**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

**Comment by satiromarra** [comment]
@laborer123 What port do you have? By ftp it must be 21.
