### ISSUE TITLE
Garbled Characters Issue

### ISSUE THREAD

**Issue by hysnwy** [satiromarra/vscode-sftp#56]
Hi @satiromarra
When the file name contains Chinese characters, it appears as garbled characters. Could you please help me resolve this compatibility issue?

**Comment by satiromarra** [comment]
Hi @hysnwy 
I have tried several tests with file names with Chinese characters, create, rename, upload, download ... and I had no problems.
If you have an FTP connection, check the option "Charset Mode: BINARY or ASCII"

Can you give me more directions?
