### ISSUE TITLE
When adding multiple profiles, port should be number, but string is written instead, causing an error

### ISSUE THREAD

**Issue by ayuayue** [satiromarra/vscode-sftp#57]
win11 vscode ,extension is newest.

**Comment by satiromarra** [comment]
@ayuayue  From the UI?

**Comment by ayuayue** [comment]
> @ayuayue From the UI?

yes like this

![image](https://github.com/satiromarra/vscode-sftp/assets/44837611/509c4162-808b-4891-abd6-06ecb191947c)

**Comment by satiromarra** [comment]
Can you try this version? [v1.18.0-dev](https://github.com/satiromarra/vscode-sftp/releases/download/v1.18.0-dev/code-sftp-1.18.0-dev.vsix)
It fixes that bug and has dependency updates.
