### ISSUE TITLE
What's this fork ?

### ISSUE THREAD

**Issue by Natizyskunk** [satiromarra/vscode-sftp#61]
Please stop ignoring me and the others on my fork. Can you please do a pull request of all your work so we can have everything in one place ? 🙂

**Comment by ankeorum** [comment]
Just give the same response he does and the same support and maybe a fork would be worth, in the meantime, this guy's giving me best support response than your bigger "official build"

**Comment by Natizyskunk** [comment]
To be clear, I'm the official maintainer of this extension since Liximomo has set his own to deprecated in favor of mine. I've been working hard to fix a lot of things and i've updated more than 30 new releases with lot of improvements and stability fixes and bring new features for two years now. I don't want to rush new features as I prefer to have a long-term stable project. Just so you know, @satiromarra has removed every mention of my work and is not even crediting me or Liximomo and the original work we've done. He's actually not giving a good side of him. I can't always be available just because you want it. As a fact he has forked my work and is taking all the credit for it without even mentioning us (liximomo or me) in the README. That's really not the way to do it.
I actually dont mind the fork, I even think that's a great idea if we can keep all the work centralized in one place. If @satiromarra isn't able to communicate and do this the right way it's not my fault ^^ If he was that implicated he would have reached to me in the first place and wait for my answer instead of ignoring me when i wasn't able to work on the project because of personal reasons. I've also a full time job that's taking me like almost 50 hours per week so I can't always be as reactive as I would like. Also just so you now, he's never responding or answering, if he was I would be more than happy to work with him to have the best of our two fork to make one big and better one. But as I said and other people also saw, he's just ignoring us. So for now I'll keep my version up-to-date and as the only official one. Just use the one you prefer. 

PS : a lot of his features are already available in mine + some others that I'm currently working on.

**Comment by satiromarra** [comment]
@Natizyskunk Good job, you've spent more time bullying me than improving the "official extension" ^^

What's with all the bullying? What do you want from me, my code, to remove my extension from the repository or both?

**Comment by satiromarra** [comment]
@Natizyskunk Do you like my new readme, happy?

**Comment by satiromarra** [comment]
By the way, do you know that the code is under the MIT license?

**Comment by Natizyskunk** [comment]
> @Natizyskunk Good job, you've spent more time bullying me than improving the "official extension" ^^
> 
> What's with all the bullying? What do you want from me, my code, to remove my extension from the repository or both?

@satiromarra Where do I bully you ? I'm only saying fact. I never failed you in respect. I even stated that i would like to work with you. I'm actually not ignoring you AFAIK.

I've updated my comment on my repo and I've mentionned you in it so you can see it. Please reach out to me in private so we can discuss this further. I actually don't mind your work at all, the only thing I asked was some credit to the original liximomo's work and mine. I dind't understand why you wouldn't answer us and make a pull request even after other people asked you for it and simply started to ignore us. It's sad to see that I had to reach out in public to have a response from you...

I actually know that it's under the MIT license and that's why I would be more than happy to work with you to make one amazing vscode extension. But if you want to make your own version, that's completely ok and your right, juste remove all my previous work from it then or at least add some credits 🙂
