### ISSUE TITLE
Rejected data connection for transfer, IP addresses of control and data connection do not match

### ISSUE THREAD

**Issue by jdanign** [satiromarra/vscode-sftp#62]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/satiromarra/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
It seems that the connection is established when Visual Studio Code starts and the extension is loaded. When switching to VPN, the connection still alive and files are rejected because the connection IP is no longer the same than files sent.

**Expected behavior**
It would be interesting to add a button or command to easily restart the FTP connection.

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - VSCode Version [1.66.1]
 - Extension Version [1.18.1]

**Extension Logs from Startup** - *required*
  [error] Error: Directoryname not valid
	at F (c:\Users\Dani\.vscode\extensions\satiromarra.code-sftp-1.18.1\dist\extension.js:2:70809)
	at p.<anonymous> (c:\Users\Dani\.vscode\extensions\satiromarra.code-sftp-1.18.1\dist\extension.js:2:71533)
	at p.emit (node:events:390:28)
	at p._write (c:\Users\Dani\.vscode\extensions\satiromarra.code-sftp-1.18.1\dist\extension.js:2:84370)
	at writeOrBuffer (node:internal/streams/writable:389:12)
	at _write (node:internal/streams/writable:330:10)
	at p.Writable.write (node:internal/streams/writable:334:10)
	at Socket.h (c:\Users\Dani\.vscode\extensions\satiromarra.code-sftp-1.18.1\dist\extension.js:2:73905)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)

**Comment by satiromarra** [comment]
@jdanign 
 The ftp connection is established when it is used, never when opening vscode.
I use vpn and have had no problems with the connections.
Enable verbose and debug mode and check the output tab.

**Comment by jdanign** [comment]
So, each time when I save a file new ftp connexion is created and closed?

The FileZilla server log Sais that the IP connection and IP transferred are different.

**Comment by satiromarra** [comment]
When you first use the ftp connection, it opens it and keeps it open, but it never opens the connection just by opening vscode.

In case the error connection will be displayed a message, then if you save the file again it will be reconnected.

So, let's see if I understood you correctly, you are using the ftp and during that use you activate the vpn the ftp stops working?

If you hover the mouse over the name of the connection, some options will appear:![image](https://github.com/satiromarra/vscode-sftp/assets/1863162/8210dcaf-6a31-41f5-9a2f-f01701352677)

**Comment by jdanign** [comment]
> When you first use the ftp connection, it opens it and keeps it open, but it never opens the connection just by opening vscode.
> 
> In case the error connection will be displayed a message, then if you save the file again it will be reconnected.
> 
> So, let's see if I understood you correctly, you are using the ftp and during that use you activate the vpn the ftp stops working?
> 
> If you hover the mouse over the name of the connection, some options will appear:![image](https://user-images.githubusercontent.com/1863162/246440530-8210dcaf-6a31-41f5-9a2f-f01701352677.png)


Sorry, but this does not work. VSC says: "Rejected data connection for transfer of "***", IP addresses of control and data connection do not match".

If I open the sftp.json config file and I save this file, the connection ends and start new one, the only way it looks like work.

**Comment by satiromarra** [comment]
@jdanign 
Can you try this beta? [v1.18.2-beta](https://github.com/satiromarra/vscode-sftp/releases/download/v1.18.2-beta/code-sftp-1.18.2-beta.vsix)
I have added the "Reconnect" icon
![image](https://github.com/satiromarra/vscode-sftp/assets/1863162/758e8ccd-76f8-4918-b40b-3c8b9db193cc)

**Comment by jdanign** [comment]
> @jdanign Can you try this beta? [v1.18.2-beta](https://github.com/satiromarra/vscode-sftp/releases/download/v1.18.2-beta/code-sftp-1.18.2-beta.vsix) I have added the "Reconnect" icon ![image](https://user-images.githubusercontent.com/1863162/246602167-758e8ccd-76f8-4918-b40b-3c8b9db193cc.png)

Yeah, it works!! Thank you
