### ISSUE TITLE
I'm trying to connect to the AWS server with regular FTP, but it just keeps trying and there is no error message.

### ISSUE THREAD

**Issue by comonetso** [satiromarra/vscode-sftp#63]
The configuration file looks like this

{
    "name": "Food",
    "host": "xxxxxxx",
    "protocol": "ftp",
    "port": 21,
    "username": "xxxx",
    "password": "xxxxxx",
    "remotePath": "/docs",
    "uploadOnSave": False,
    "useTempFile": False,
    "openSsh": False,
    "ignore": [],
    "charset": "utf8",
    "showHidden": True,
    "secure": False,
    "profiles": {}
}

In the terminal, the above configuration should work fine.
The good connection in the terminal means that there is no problem connecting to this FTP server from your computer to the AWS server.

Also, with the above configuration, other hosts other than AWS will be connected well.
So it looks like the configuration is fine.

However, when I try to connect to AWS with the above configuration, it keeps trying to connect and keeps trying even after the timeout, and there is no error message. 

I wonder if the SFTP is going through another server.

I only have port 21 on my current machine open in the security group of ASW.
I've been struggling with this for a few days now.

Please help me

**Comment by satiromarra** [comment]
@comonetsoHave you tried these options?:
```json
"port": 21,
"secure": true,
```

**Comment by comonetso** [comment]
secure: true

If set as above, the

Unable to secure connection(s)
it comes out like this

Otherwise, an infinite number of connection attempts will be made. 
No timeout

my sftp.json is

[
    {
        "name": "Food",
        "host": "13.124.251.204",
        "protocol": "ftp",
        "uploadOnSave": true,
        "useTempFile": true,
        "port": 21,
        "username": "******",
        "ignore": [ ],
        "context": "./",
        "remotePath": "~/",
        "watcher": {},
        "remoteExplorer": {"filesExclude": []},
        "password": "*********",
        "charset": "ascii",
        "showHidden": false,
        "profiles": {}
    }
]

**Comment by satiromarra** [comment]
I had understood that you wanted to use ftps. To use "ftp",  have you tried this configuration?
```json
{
  "name": "Food",
  "host": "xxxxxxx",
  "protocol": "ftp",
  "port": 21, 
  "username": "xxxx",
  "password": "xxxxxx",
  "remotePath": "/docs",
  "charset": "utf8",
  "showHidden": true,
}
```

**Comment by comonetso** [comment]
Thanks for the answer.

I tried the settings you suggested

Same thing, infinite connections, no errors, frustrating,

**Comment by comonetso** [comment]
> I had understood that you wanted to use ftps. To use "ftp", have you tried this configuration?
> 
> ```json
> {
>   "name": "Food",
>   "host": "xxxxxxx",
>   "protocol": "ftp",
>   "port": 21, 
>   "username": "xxxx",
>   "password": "xxxxxx",
>   "remotePath": "/docs",
>   "charset": "utf8",
>   "showHidden": true,
> }
> ```

Thanks for the answer.

I tried the settings you suggested.

Same thing, infinite connections, no errors, frustrating,

**Comment by comonetso** [comment]
It would be even worse if there was an error message, but since it only tries to connect infinitely, there is no error message.

**Comment by satiromarra** [comment]
and this? if your server is vsftpd: https://github.com/satiromarra/vscode-sftp/wiki/FAQ#error-session-reuse-required
```json
{
  "name": "xxx",
  "password": "xxx",
  "username": "xxx",
  "host": "xxx",
  "protocol": "ftp",// <- this
  "port": 21,// <- this
  "secure": true, // <- this
  "secureOptions":  {"rejectUnauthorized": false, "secureProtocol" :"TLSv1_2_method"} // <- and this
}
```

**Comment by comonetso** [comment]
If you still get
Unable to secure connection(s)
error
when I set secure to true, but when I change it to false, it's an infinite connection and the

**Comment by satiromarra** [comment]
Is the authentication with username/password or with rsa key?

**Comment by comonetso** [comment]
I didn't open the data transfer port for VSFTP in AWS

Port 21 is needed for sending commands, and there is a separate data transfer port. 

Thank you.
