### ISSUE TITLE
Upload/Download links in Open Editors

### ISSUE THREAD

**Issue by andreysamode** [satiromarra/vscode-sftp#67]
In the Explorer context menu, there are the Upload/Download options:
<img width="268" alt="Screen Shot 2023-06-27 at 10 06 08 AM" src="https://github.com/satiromarra/vscode-sftp/assets/444565/8c65f21d-cc30-45d5-a133-97bb2ab6472a">

In the Open Editors view, the Upload/Download options are missing:
<img width="257" alt="Screen Shot 2023-06-27 at 10 05 28 AM" src="https://github.com/satiromarra/vscode-sftp/assets/444565/5116edd3-4877-4e00-838b-3a43366b2539">

Could we have them enabled there as well?

Thanks!

**Comment by satiromarra** [comment]
@mrandrey I think vscode doesn't give access to that pane and you can't add options to the menu.

**Comment by andreysamode** [comment]
Ah, that's too bad. Thanks for looking into it.
