### ISSUE TITLE
Refresh button does not work

### ISSUE THREAD

**Issue by jdanign** [satiromarra/vscode-sftp#71]
**Do you read the FAQ?**
- [X] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Refresh button does not do anything. I need to refresh the file list but it does not update when I refresh folder or connection.

**To Reproduce**
Upload new file to folder.
Refresh folder or connection.
It does not update file list.

**Expected behavior**
The file list should be updated when refresh

**Screenshots**
![CAP](https://github.com/satiromarra/vscode-sftp/assets/64546490/0aa83629-86e2-4d30-bf28-45be3a0940e8)

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - VSCode Version [1.66.1]
 - Extension Version [v1.18.2-beta]

**Comment by satiromarra** [comment]
@jdanign Activate in debug mode of the extension, reload vscode, open the "exit" tab and select "sftp". Do you see any errors?

**Comment by jdanign** [comment]
> @jdanign Activate in debug mode of the extension, reload vscode, open the "exit" tab and select "sftp". Do you see any errors?

No, there is no errors. It looks like filelist does not update when click on refresh button, I've tried with folder refresh button, connection refresh button and sftp explorer refresh button.

**Comment by satiromarra** [comment]
Activating the debug mode, a message must appear, showing the reading of the directory and what it contains.

**Comment by jdanign** [comment]
> Activating the debug mode, a message must appear, showing the reading of the directory and what it contains.

I have seen the problem. Filelist is updated when his parent directory hides his own files. 
For example: I have a directory as /myfolder/file.js, if I upload a new file to /myfolder/, the extension does not update de filelist while the tree shows the content of /myfolder/. If I hide the content of /myfolder/ and I upload the file, the extension updates the filelist when I show the content of /myfolder/.

**Comment by satiromarra** [comment]
@jdanign try this [beta](https://github.com/satiromarra/vscode-sftp/releases/download/v1.18.2-beta2/code-sftp-1.18.2-beta2.vsix)
