### ISSUE TITLE
Automatic "Reveal in Remote Explorer" when switch to a tab

### ISSUE THREAD

**Issue by C1977** [satiromarra/vscode-sftp#81]
I would like to have an option to automaticly "Reveal in Remote Explorer" when a tab is selected. E.g. I open file hurz.php in folder 1 and glop.php in folder 2 (or other remote system). Then I switch between the VSCode tabs sometimes.  Lets say I switch to glop.php tab - by activating right-click "Reveal in Remote Explorer" I can make VSCode to open the tree and position of the glop.php. But would be very good if this can be done automatically by an option.

![grafik](https://github.com/satiromarra/vscode-sftp/assets/36223435/078b8495-a8a5-459a-b8f1-844ccd8ee827)

**Comment by satiromarra** [comment]
@C1977 
That's a problem that I haven't managed to fix yet.
