### ISSUE TITLE
sshConfig not working with ProxyCommand

### ISSUE THREAD

**Issue by sickerin** [satiromarra/vscode-sftp#89]
**Do you read the FAQ?**
- [X] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**

- Proxy command doesn't seem to work with the extension
- `Host` needs to be exact in ssh config

I saw this issue in the other repo and shared my results https://github.com/Natizyskunk/vscode-sftp/issues/382
For me `SFTP: Open SSH in Terminal` works, but when using the extension to do anything else, I get `getaddrinfo ENOTFOUND`. The first issue seems to be that this part `Section for 'target' found with Host or Match`, if I changed my Host to only have the words `Host target`, I don't get this issue, but the `Host` should be allowed to have multiple aliases. Even if that passes, it seems I'm not able to connect still.
My example ssh config. 

```
Host jump
    HostName jump.io
    Port 2222
    IdentityFile ~/.ssh/id_rsa

Host target target10 10.10.10.10
    HostName 10.10.10.10
    ProxyCommand ssh jump -W %h:%p
```
And example sftp.json

```
{
    "name": "target-example",
    "username": "root",
    "host": "target",
    "protocol": "sftp",
    "port": 21,
    "secure": true,
    "sshConfigPath": "~/.ssh/config",
    "privateKeyPath": "~/.ssh/id_rsa",
    "remotePath": "/data/me/",
    "uploadOnSave": false,
    "openSsh": true
}
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 12.6.7
 - VSCode Version: 1.81.1
 - Extension Version: v1.18.1

**Extension Logs from Startup** - *required*
This is the log after I modify my ssh config to not include any aliases.
```
[2023-09-12 16:08:12] [info] Section for 'target' found with Host or Match
[2023-09-12 16:08:12] [debug] Custom crypto binding not available
[2023-09-12 16:08:12] [debug] Local ident: 'SSH-2.0-ssh2js1.13.0'
[2023-09-12 16:08:12] [debug] Client: Trying 10.10.10.10 on port 21 ...
[2023-09-12 16:08:22] [debug] Outbound: Sending DISCONNECT (11)
[2023-09-12 16:08:22] [debug] Socket closed
```

**Comment by satiromarra** [comment]
And so?
`ProxyCommand ssh -W "%h:%p" firewall.example.org`

**Comment by Oaklight** [comment]
> And so? `ProxyCommand ssh -W "%h:%p" firewall.example.org`

No, it doesn't work either. In some cases, the jump server cannot be logged in manually. At least in my organization, they bar everyone from the login jumper and ask us to submit ssh keys via a web portal.
